[package]
name = "alfred"
version = "0.1.0"
edition = "2021"

[dependencies]
pty-process = "0.5.3"
ratatui = { version = "0.30.0", features = ["crossterm"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_yaml = "0.9.34"
